### ISSUE TITLE
定时列表 指令执行错误

### ISSUE THREAD

**Issue by qllokirin** [velor2012/nonebot_plugin_reminder#1]
似乎是没有target字段，翻阅了一下源码似乎也没有写入target的操作，我把这行读取target的操作删除了就可以正常运行了

> 09-25 16:58:13 [SUCCESS] nonebot | OneBot V11 263181736 | [message.group.normal]: Message 455286677 from 2456590695@[群:627734379] '[at:qq=263181736,name=@呱唧（瓜大机器人）] 定时列表'
09-25 16:58:13 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_reminder, lineno=81)
09-25 16:58:13 [INFO] nonebot_plugin_reminder | CONFIG: {'reminder_qpd7r': {'id': 'reminder_qpd7r', 'bot': '263181736', 'time': '17:00', 'data': '打卡!!!', 'repeat': '1', 'userId': 2456590695, 'groupId': 627734379, 'url': None, 'status': 1, 'type': 'normal'}}
09-25 16:58:13 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_reminder, lineno=81) running complete
09-25 16:58:13 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_reminder, lineno=81) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/usr/local/lib/python3.10/dist-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 577, in run
    server.run()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/usr/local/lib/python3.10/dist-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_reminder/__init__.py", line 220, in list_matcher_handle
    msg.append(item2string(item))
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_reminder/data_utils.py", line 39, in item2string
    目标: {item['target']} \n\
KeyError: 'target'

**Comment by velor2012** [comment]
是我疏忽了，感谢反馈！

**Comment by qllokirin** [comment]
请问大佬有意向&有时间增加一些新功能吗
比如输入定时可以发`定时 18.00`因为手机使用数字九格时右侧会有点`.`这个符号而冒号`:`要去符号里面找，或者`18点00分`之类的？
`选择执行间隔时`感觉如果能增加 今天 明天 后天 之类的选项就更好了
`某天回复具体日期，格式为yyyy-mm-dd,如2023-01-03`感觉如果能匹配x月x日就好了，因为`-`不在键盘字符里，需要点开符号 感觉不太方便
这么晚打扰了
